#!/usr/bin/env bun
/**
 * Generate OMP's `models.yml` from this gateway's live public catalog.
 *
 * Why generated rather than hand-written: OMP needs per-model capability
 * metadata that its own discovery cannot obtain, so the same facts would
 * otherwise be maintained in two files and drift. `model_registry.yaml` owns
 * capability facts, while GET /v1/models decides which of those facts are
 * actually usable by the currently logged-in gateway.
 *
 * What OMP's proxy discovery does and does not read from GET /v1/models:
 *   reads  — id, supported_endpoint_types, context_length
 *   ignores — the whole `capabilities` object
 * Everything else (reasoning / thinking / input modalities) it looks up by
 * model id in its own bundled catalog. Channel-qualified ids are not in that
 * catalog, so without these overrides every model silently degrades to
 * reasoning:false + input:[text] — thinking levels stop working and images
 * get rejected.
 *
 * Usage:  bun run scripts/gen_omp_models.ts [outfile]
 *         (default outfile: ~/.omp/agent/models.yml)
 */

import * as os from 'os'
import * as path from 'path'
import { listRegistry, type RegistryEntry } from '../src/model_registry.js'

const GATEWAY_BASE_URL = process.env.OMP_GATEWAY_BASE_URL ?? 'http://localhost:8085/v1'

/**
 * OMP distinguishes a numeric Anthropic-style budget from a semantic tier.
 * Claude and DeepSeek take a token budget; Gemini and Codex take an effort
 * string, so declaring the wrong mode makes the level silently inert.
 */
function thinkingMode(entry: RegistryEntry): 'anthropic-budget-effort' | 'effort' {
  return /claude|deepseek/.test(entry.upstream) ? 'anthropic-budget-effort' : 'effort'
}

function render(entries: readonly RegistryEntry[]): string {
  const out: string[] = [
    '# GENERATED by agent-all-sdk-ts/scripts/gen_omp_models.ts — do not hand-edit.',
    '# Source of truth: agent-all-sdk-ts/src/model_registry.yaml',
    '# Regenerate:      bun run scripts/gen_omp_models.ts',
    '#',
    '# id shape is <channel>-<model>, and the separator must be "-", never "/":',
    "# OMP's proxy discovery silently drops catalog entries whose id contains a",
    '# slash (verified with a fixture serving both shapes — only the dashed id was',
    '# ever selected). It reserves "/" for the provider/model level.',
    '#',
    '# The channel prefix is not cosmetic: local-* spends the local OAuth',
    '# subscription, ccr-* spends cc-relay credit. Same weights, different bill.',
    '',
    'providers:',
    '  local-gw:',
    `    baseUrl: ${GATEWAY_BASE_URL}`,
    '    api: anthropic-messages',
    '    auth: none',
    '    disableStrictTools: true',
    '    discovery:',
    '      type: proxy',
    '',
    '    modelOverrides:',
  ]

  let channel = ''
  for (const entry of entries) {
    if (entry.channel !== channel) {
      channel = entry.channel
      out.push(`      # ── ${channel} ${'─'.repeat(Math.max(0, 52 - channel.length))}`)
    }
    out.push(`      ${entry.id}:`)
    out.push(`        name: ${entry.id}`)
    out.push(`        reasoning: ${!!entry.thinking}`)
    if (entry.thinking) {
      const efforts = entry.thinking.efforts.join(', ')
      out.push(
        `        thinking: { mode: ${thinkingMode(entry)}, efforts: [${efforts}], ` +
          `defaultLevel: ${entry.thinking.default}, supportsDisplay: true }`,
      )
    }
    out.push(`        input: [${entry.images ? 'text, image' : 'text'}]`)
    out.push(`        supportsTools: ${entry.tools}`)
    out.push(`        contextWindow: ${entry.contextWindow}`)
    out.push(`        maxTokens: ${entry.maxOutputTokens}`)
  }
  return out.join('\n') + '\n'
}

interface GatewayModelCatalogResponse {
  readonly object: 'list'
  readonly data: readonly { readonly id: string }[]
}

/** Refuse to write a client config from candidates that the running gateway did not publish. */
async function loadLiveGatewayModelIds(baseUrl: string): Promise<ReadonlySet<string>> {
  const catalogUrl = new URL('models', `${baseUrl.replace(/\/$/, '')}/`).toString()
  const response = await fetch(catalogUrl)
  if (!response.ok) {
    throw new Error(`Cannot generate OMP models: GET ${catalogUrl} returned HTTP ${response.status}`)
  }
  const catalog = await response.json() as GatewayModelCatalogResponse
  if (catalog.object !== 'list' || !Array.isArray(catalog.data)) {
    throw new Error(`Cannot generate OMP models: GET ${catalogUrl} did not return a models list`)
  }
  const ids = new Set(catalog.data.map(model => model?.id).filter((id): id is string => typeof id === 'string'))
  if (ids.size === 0) throw new Error(`Cannot generate OMP models: GET ${catalogUrl} published no models`)
  return ids
}

const target =
  process.argv[2] ?? path.join(os.homedir(), '.omp', 'agent', 'models.yml')
const liveModelIds = await loadLiveGatewayModelIds(GATEWAY_BASE_URL)
const entries = listRegistry().filter(entry => liveModelIds.has(entry.id))
if (entries.length === 0) {
  throw new Error('Cannot generate OMP models: no live gateway model has a registry capability declaration')
}
await Bun.write(target, render(entries))
console.log(`wrote ${entries.length} live model overrides to ${target}`)
